<?php

/* $Id$ */
/* site configuration for art.gnome.org */

$linkbar = array (
	"news" => array(
   	"url" => "/index.php",
      "width" => "",
      "height" =>"",
      "indent" => "0",
      "alt" => "NEWS"),
	"updates" => array(
   	"url" => "/updates.php",
      "width" => "",
      "height" =>"",
      "indent" => "0",
      "alt" => "UPDATES"),
	"backgrounds" => array(
   	"url" => "/backgrounds/",
      "width" => "",
      "height" => "",
      "indent" => "0",
      "alt" => "BACKGROUNDS"),
   "backgrounds_gnome" => array(
   	"url" => "/backgrounds/gnome/",
      "width" => "",
      "height" => "",
      "indent" => "1",
      "alt" => "GNOME"),
   "backgrounds_other" => array(
   	"url" => "/backgrounds/other/",
      "width" => "",
      "height" => "",
      "indent" => "1",
      "alt" => "Other"),
   "themes" => array(
   	"url" => "/themes/",
      "width" => "",
      "height" => "",
      "indent" => "0",
      "alt" => "THEMES"),
   "themes_gdm_greeter" => array(
   	"url" => "/themes/gdm_greeter/",
      "width" => "",
      "height" => "",
      "indent" => "1",
      "alt" => "GDM Greeter"),
   "themes_gtk" => array(
   	"url" => "/themes/gtk/",
      "width" => "",
      "height" => "",
      "indent" => "1",
      "alt" => "GTK+ 1.2"),
   "themes_gtk2" => array(
   	"url" => "/themes/gtk2/",
      "width" => "",
      "height" => "",
      "indent" => "1",
      "alt" => "GTK+ 2.0"),
   "themes_metacity" => array(
   	"url" => "/themes/metacity/",
      "width" => "",
      "height" => "",
      "indent" => "1",
      "alt" => "Metacity"),
   "themes_metatheme" => array(
   	"url" => "/themes/metatheme/",
      "width" => "",
      "height" => "",
      "indent" => "1",
      "alt" => "Metatheme"),
   "themes_nautilus" => array(
   	"url" => "/themes/nautilus/",
      "width" => "",
      "height" => "",
      "indent" => "1",
      "alt" => "Nautilus"),
   "themes_sawfish" => array(
   	"url" => "/themes/sawfish/",
      "width" => "",
      "height" => "",
      "indent" => "1",
      "alt" => "Sawfish"),
   "themes_sounds" => array(
   	"url" => "/themes/sounds/",
      "width" => "",
      "height" => "",
      "indent" => "1",
      "alt" => "Sounds"),
   "themes_splash_screens" => array(
   	"url" => "/themes/splash_screens/",
      "width" => "",
      "height" => "",
      "indent" => "1",
      "alt" => "Splash Screens"),
   "themes_other" => array(
   	"url" => "/themes/other/",
      "width" => "",
      "height" => "",
      "indent" => "1",
      "alt" => "Other..."),
   "icons" => array(
   	"url" => "/icons.php",
      "width" => "",
      "height" => "",
      "indent" => "0",
      "alt" => "ICONS"),
   "tips" => array(
   	"url" => "/tips.php",
      "width" => "",
      "height" => "",
      "indent" => "0",
      "alt" => "TIPS &amp; TRICKS"),
   "faq" => array(
   	"url" => "/faq.php",
      "width" => "",
      "height" => "",
      "indent" => "0",
      "alt" => "FAQ"),
   "submit" => array(
   	"url" => "/submit.php",
      "width" => "",
      "height" => "",
      "indent" => "0",
      "alt" => "SUBMIT"),
   "contact" => array(
   	"url" => "/contact.php",
      "width" => "",
      "height" => "",
      "indent" => "0",
      "alt" => "CONTACT"),
	"links" => array(
   	"url" => "/links.php",
      "width" => "",
      "height" => "",
      "indent" => "0",
      "alt" => "LINKS")
);

$pill_array = array (
	"news" => array(
   	"image" => "NEWS-Pill.png",
      "width" => "154",
      "height" =>"62",
      "alt" => "NEWS"),
	"updates" => array(
   	"image" => "Updates-Pill.png",
      "width" => "188",
      "height" =>"62",
      "alt" => "UPDATES"),
	"backgrounds" => array(
   	"image" => "BACKGROUNDS-Pill.png",
      "width" => "248",
      "height" => "62",
      "alt" => "BACKGROUNDS"),
   "backgrounds_gnome" => array(
   	"image" => "GNOME-Pill.png",
      "width" => "368",
      "height" => "62",
      "alt" => "BACKGROUNDS - GNOME"),
   "backgrounds_other" => array(
   	"image" => "BackOther-Pill.png",
      "width" => "368",
      "height" => "62",
      "alt" => "BACKGROUNDS - OTHER"),
   "themes" => array(
   	"image" => "THEMES-Pill.png",
      "width" => "183",
      "height" => "62",
      "alt" => "THEMES"),
   "themes_gdm_greeter" => array(
   	"image" => "Greeter-Pill.png",
      "width" => "348",
      "height" => "62",
      "alt" => "THEMES - GDM GREETER"),
   "themes_gtk" => array(
   	"image" => "GTK1-Pill.png",
      "width" => "303",
      "height" => "62",
      "alt" => "THEMES - GTK+ 1.2"),
   "themes_gtk2" => array(
   	"image" => "GTK2-Pill.png",
      "width" => "313",
      "height" => "62",
      "alt" => "THEMES - GTK+ 2.0"),
   "themes_metacity" => array(
   	"image" => "Metacity-Pill.png",
      "width" => "303",
      "height" => "62",
      "alt" => "THEMES - Metacity"),
   "themes_metatheme" => array(
   	"image" => "Metatheme-Pill.png",
      "width" => "323",
      "height" => "62",
      "alt" => "THEMES - Metatheme"),
   "themes_nautilus" => array(
   	"image" => "Nautilus-Pill.png",
      "width" => "293",
      "height" => "62",
      "alt" => "THEMES - Nautilus"),
   "themes_sawfish" => array(
   	"image" => "Sawfish-Pill.png",
      "width" => "292",
      "height" => "62",
      "alt" => "THEMES - Sawfish"),
   "themes_sounds" => array(
   	"image" => "Sounds-Pill.png",
      "width" => "292",
      "height" => "62",
      "alt" => "THEMES - Sounds"),
   "themes_splash_screens" => array(
   	"image" => "Splash-Pill.png",
      "width" => "368",
      "height" => "62",
      "alt" => "THEMES - Splash Screens"),
   "themes_other" => array(
   	"image" => "Other-Pill.png",
      "width" => "293",
      "height" => "62",
      "alt" => "THEMES - Other"),
   "icons" => array(
   	"image" => "ICONS-Pill.png",
      "width" => "154",
      "height" => "62",
      "alt" => "ICONS"),
   "tips" => array(
   	"image" => "TIPS-Pill.png",
      "width" => "248",
      "height" => "62",
      "alt" => "Tips &amp; Tricks"),
   "faq" => array(
   	"image" => "FAQ-Pill.png",
      "width" => "135",
      "height" => "62",
      "alt" => "FAQ"),
   "contact" => array(
   	"image" => "CONTACT-Pill.png",
      "width" => "188",
      "height" => "62",
      "alt" => "CONTACT"),
	"links" => array(
   	"image" => "LINKS-Pill.png",
      "width" => "154",
      "height" => "62",
      "alt" => "LINKS"),
	"copyright" => array(
   	"image" => "Copyright-Pill.png",
      "width" => "248",
      "height" => "62",
      "alt" => "COPYRIGHT"),
   "screenshots" => array(
   	"image" => "Screenshots-Pill.png",
      "width" => "237",
      "height" => "62",
      "alt" => "SCREENSHOTS"),
	"submit" => array(
   	"image" => "Submit-Pill.png",
      "width" => "188",
      "height" => "62",
      "alt" => "SUBMIT")
    
);
/*

$sys_icon_type_array = array(
	"gtk-stock" => array(
   	"realname" => "Gtk+ Stock Icons",
      "tarball_name" => "tarball (64 kB)",
      "tarball_filename" => "gtk-stock_all.tar.gz",
      "image" => "stock_home_24.png"),
   "nautilus-emblems" => array(
    	"realname" => "Nautilus Emblems",
      "tarball_name" => "tarball (110 kB)",
      "tarball_filename" => "nautilus-emblems_all.tar.gz",
      "image" => "Gridlock.png"),
   "gnome-people" => array(
    	"realname" => "GNOME People",
      "tarball_name" => "tarball (160 kB)",
      "tarball_filename" => "gnome-people_all.tar.gz",
      "image" => "Tigert.png"),
   "other" => array(
    	"realname" => "Misc. Icons",
      "tarball_name" => "tarball (3.2 MB)",
      "tarball_filename" => "other_all.tar.gz",
      "image" => "Boot.png"),
   "large" => array(
    	"realname" => "Larger Icons",
      "tarball_name" => "tarball (1.2 MB)",
      "tarball_filename" => "large_all.tar.gz",
      "image" => "Elysium.png"),
);
*/

$sys_icon_dir = "/usr/local/www/art.gnome.org/images/icons";

$valid_image_ext = array ("png","xpm","gif","jpg","jpeg","tiff");

$thumbnails_per_page_array = array("12"=>12,"24"=>24,"All"=>1000);
?>
